services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ps-app
    ports:
      - "30000:30000"
      - "30001:30001"
    depends_on:
      - postgres
    networks:
      - ps

  postgresql:
    image: postgres:14-alpine
    container_name: ps-psql
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=prodservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ps

networks:
  ps:
    name: ps